steps:
- name: 'docker'
  entrypoint: '/bin/sh'
  args: 
  - '-e'
  - '-c'
  - |-
    apk add bash
    docker login --username=coquinone --password=$_PASS
    ./build_push_update_images.sh "prod-$SHORT_SHA" --prefix=coquinone
